#!/bin/sh
echo 'Commit-MSG Hook: Adding commit message to changed .SQL files'
for sql in `git diff-tree -r --name-only --no-commit-id master`; do
  echo $sql
  ext=${sql: -4}
  if [ "$ext" = ".sql" ] 
  then
	 `(cat $sql | cscript.exe //NoLogo c:/commit-msg-clean.vbs | cscript.exe //NoLogo c:/commit-msg-smudge.vbs "$sql" ) > $sql.new.hook`
     `cat $sql.new.hook > $sql`
	 `rm $sql.new.hook`
  fi
done

echo 'Commit-MSG Commit Hook: Commit message change finished.'